koinos/koinos-docs

docs/content/quickstart/developers-guide.md
docs/content/quickstart/running-a-koinos-node.md
docs/index.rst

Add a developer guide to the documentation

---

docs/architecture/overriding-system-calls.md
docs/architecture/system-calls.md
docs/index.rst

Document system calls which are not able to be fully overridden

---

docs/architecture/contract-abi.md
docs/architecture/microservice.md
docs/architecture/serialization.md
docs/architecture/system-calls.md
docs/quickstart/running-a-koinos-node.md
docs/tutorials/custom-types-contract.md

Resolves koinos/koinos-internal#127.

Update existing documentation to match latest developments

---

docs/quickstart/contract-developer-guide.md

Add assemblyscript section and update C++ section
Resolves https://github.com/koinos/koinos-internal/issues/128.

Update contract developer guide

---

docs/quickstart/block-production.md

Update block production guide with appropriate contracts

fix: update pob and vhp contracts to mainnet

---

docs/quickstart/running-a-koinos-node.md

Resolves #61
Updates documentation on running a Koinos node.

Update node docs

---

docs/quickstart/running-a-koinos-node.md

Update `docker-compose` to `docker compose`

---

docs/overview/tokenomics.md

Resolves #81
Adds documentation of the tokenomics of Koinos

#81: Add tokenomics documentation

---

docs/overview/smart-contracts.md

Resolves #80.
Adds a smart contract overview page.

#80: Add a smart contract overview page

---

docs/overview/blockchain-basics.md
docs/overview/proof-of-burn.md

Resolves #79.
Adds an overview on Proof-of-Burn.

Proof of burn

---

docs/architecture/microservices.md
docs/architecture/system-calls.md
mkdocs.yml

Resolves #107.
Migrates system call documentation.
* Adds `get_contract_metadata` system call
* Adds list of thunks and a summary about them

System calls & thunks

---

docs/architecture/interprocess-communication.md
docs/architecture/microservices.md
mkdocs.yml

Resolves #108.
Migrates interprocess communication documentation with slight changes.

Interprocess communication

---

docs/architecture/interprocess-communication.md
docs/architecture/microservices.md
docs/architecture/smart-contracts.md
mkdocs.yml

Resolves #109.
Migrate smart contract documentation to new site.

Smart contracts

---

docs/architecture/contract-abi.md
docs/architecture/microservices.md
mkdocs.yml

Resolves #104.
Migrates Contract ABI documentation.

Contract ABI

---

docs/developers/as-sdk.md
mkdocs.yml

Resolves #84.
Setting up and testing AssemblyScript SDK.

AssemblyScript SDK environment setup and basics

---

docs/developers/rest.md
docs/developers/rpc.md
docs/developers/swagger.json
mkdocs.yml
requirements.txt

Swagger UI

---

docs/developers/transactions.md
mkdocs.yml

Resolves #88.
Documentation on transactions.

Transactions

---

docs/developers/protobuf.md
mkdocs.yml

Resolves #91.
Adds documentation about protocol buffers for developers.

Protocol buffers

---

docs/developers/deploy-contract.md
mkdocs.yml

Resolves #93.
Migrates deploy contract guide.

Deploy contract

---

docs/developers/resource-management.md
mkdocs.yml

Resolves #92.
Basic documentation for developers about resource managment.

Resource management

---

docs/developers/authority.md
docs/developers/deploy-contract.md
docs/developers/guides/calculator.md
mkdocs.yml

Resolves #89
Adds authority documentation

#89: Add authority documentation

---

docs/developers/cli.md
mkdocs.yml

Resolves #143.
Adds documentation for the Koinos CLI.

Koinos CLI

---

docs/architecture/serialization.md

Resolves #105.
Add serialization documentation under architecture.

Add serialization documentation

---

docs/architecture/resources.md

#110: Add documentation on resources

---

docs/validators/guides/running-a-node.md
mkdocs.yml

Resolves #101
Adds guide on running a Koinos node

#101: Add guide on running a node

---

docs/validators/node-requirements.md
mkdocs.yml

Resolves  #95
Documents node requirements

95 node requirements

---

docs/validators/docker-compose-profiles.md
mkdocs.yml

Resolves #96 
Documents compose profiles

96 compose profiles

---

docs/architecture/microservices.md
docs/validators/microservices.md
mkdocs.yml

#97: Add microservice documentation for validators

---

docs/validators/configuration.md
mkdocs.yml

Resolves #99
Adds configuration documentation

99 configuration

---

docs/validators/guides/block-production.md
mkdocs.yml

Resolves #102.
Adds a block production guide.

Block production guide

---

docs/exchanges/offline-signing.md

Update nonce documentation for offline signing

---

docs/validators/node-management.md
mkdocs.yml

Resolves #100
Documents node management

100 node management

---

docs/exchanges/account-balance.md

Resolves #151.
Retrieving your account balance with Koinos CLI.

Account balance with Koinos CLI

---

docs/exchanges/create-wallet.md

Resolves #156.
Create a wallet using the Koinos CLI.

Create a wallet with Koinos CLI

---

docs/exchanges/mana.md

Resolves #165.
How to retrieve available Mana using Koinos CLI.

Mana using Koinos CLI

---

docs/exchanges/account-history.md
docs/exchanges/finality.md
docs/exchanges/head-block.md

Resolves #154
Resolves #159 
Resolves #162
These features will not be added to the CLI in the short term. We just need to document this.

Document tasks that the CLI cannot do

---

docs/exchanges/multisig.md

Resolves #169.
Resolves #168.
Documents multisig using Koilib.

Multisig using Koilib

---

docs/overview/mana.md

Explain Mana with 'Mana is a regenerative resource granted by holding KOIN that allows users to pay for transactions with time.' on top of the document
Resolves

Explain Mana in  mana.md

---

docs/architecture/proof-of-burn.md

Resolves koinos/koinos-internal#246.
Adds architecture page for PoB.

Architecture page for PoB

---

docs/developers/swagger.json
docs/exchanges/head-block.md

Resolves #163
Documents retrieving the head block with the REST API

#163: REST head block

---

docs/exchanges/account-history.md

Resolves #155
Documents retrieving account history using the REST API

#155: Add account history REST documentation

---

docs/exchanges/mana.md

Resolves #166
Adds documentation on getting Mana using the REST API.

#166: Document getting Mana using the REST API

---

docs/exchanges/account-history.md
docs/exchanges/create-wallet.md
docs/exchanges/finality.md
docs/exchanges/head-block.md
docs/exchanges/mana.md
docs/exchanges/offline-signing.md

Resolves #170 #167 #164 #161 #158 #157
Different examples on how to use Koilib

Documentation for koilib

---

docs/developers/guides/immutable.md
mkdocs.yml

Resolves koinos/koinos-internal#240.
Adds guides on making immutable contracts.

Add guide on creating immutable smart contracts

---

docs/developers/guides/staking.md
mkdocs.yml

Resolves koinos/koinos-internal#242.
Adds a token staking guide.

Add a staking guide

---

docs/developers/guides/authority.md
mkdocs.yml

Resolves koinos/koinos-internal#244

Add authority guide

---

mkdocs.yml

Resolves #202
Fix the view and edit URL prefix.

Fix edit URL

---

docs/exchanges/cli.md
docs/exchanges/jsonrpc.md
docs/exchanges/koilib.md
docs/exchanges/rest.md
mkdocs.yml

Resolves #204
Adds REST and Koilib intro for exchange documentation.

#204: Add exchange info the REST and Koilib

---

docs/developers/guides/token.md

Resolves #205.
Update the token guide to KCS-4 standard.
**Do not merge** Work in progress.

Update token guide to KCS-4
